"""Profile the raw source files before writing cleansing rules.

Reads every file of a batch exactly as received (all values as text) and
reports, per file: row count, blanks per column, duplicate rows and IDs,
the distinct values of low-cardinality columns, and the "shapes" of date and
amount values (digits replaced by 9, e.g. 2026-09-30 -> 9999-99-99).

Usage:  python -m pipeline.profile_data day1 day2 > docs/DATA_PROFILE.md
"""
import re
import sys
from collections import Counter

import pandas as pd

from pipeline.config import BATCH_FILES, get_settings, raw_path
from pipeline.readers import read_json_salvaging

ID_COLUMNS = {
    "branches": "branch_id",
    "customers": "customer_id",
    "products": "product_id",
    "transactions": "transaction_id",
}
SHAPE_COLUMNS = {"date", "timestamp", "amount", "dob", "registration_date",
                 "opened_date", "launch_date", "phone", "contact_number", "price"}
MAX_DISTINCT_TO_LIST = 15


def load_as_text(path) -> tuple[pd.DataFrame, str]:
    """Load a CSV or JSON file with every value kept as text."""
    if path.suffix == ".json":
        records, error, _lost = read_json_salvaging(path.read_text(encoding="utf-8"))
        df = pd.DataFrame(records).astype(object)
        df = df.where(df.notna(), "<missing>").astype(str)
        return df, error
    return pd.read_csv(path, dtype=str, keep_default_na=False), ""


def shape(value: str) -> str:
    return re.sub(r"[A-Za-z]", "A", re.sub(r"\d", "9", value)) if value else "<blank>"


def profile_file(path, entity: str) -> list[str]:
    df, json_error = load_as_text(path)
    out = [f"### {path.parent.name}/{path.name} ({entity})", ""]
    out.append(f"- Rows: **{len(df)}**, columns: {len(df.columns)}")
    if json_error:
        out.append(f"- **Structural defect:** {json_error}; {len(df)} objects still recoverable")
    id_col = ID_COLUMNS[entity]
    out.append(f"- Exact duplicate rows: {int(df.duplicated().sum())}")
    dup_ids = df[id_col].value_counts()
    dup_ids = dup_ids[dup_ids > 1]
    out.append(f"- `{id_col}` values appearing more than once: {len(dup_ids)}"
               + (f" (e.g. {', '.join(dup_ids.index[:5])})" if len(dup_ids) else ""))
    out += ["", "| Column | Blank | Distinct | Values / shapes |", "| --- | --- | --- | --- |"]
    for col in df.columns:
        values = df[col].astype(str)
        blanks = int((values.str.strip() == "").sum() + (values == "<missing>").sum())
        distinct = values.nunique()
        if col in SHAPE_COLUMNS:
            shapes = Counter(shape(v.strip()) for v in values)
            detail = ", ".join(f"`{s}`×{n}" for s, n in shapes.most_common(8))
        elif distinct <= MAX_DISTINCT_TO_LIST:
            counts = values.value_counts()
            detail = ", ".join(f"`{v!r}`×{n}" for v, n in counts.items())
        else:
            detail = "high-cardinality"
        out.append(f"| {col} | {blanks} | {distinct} | {detail} |")
    return out + [""]


def main(batch_ids: list[str]) -> None:
    settings = get_settings()
    lines = ["# Raw data profile", "",
             "Generated by `python -m pipeline.profile_data`. Values were read as text, exactly as received.", ""]
    for batch_id in batch_ids:
        lines += [f"## Batch `{batch_id}`", ""]
        for entity in BATCH_FILES[batch_id]:
            lines += profile_file(raw_path(settings, batch_id, entity), entity)
    print("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1:] or list(BATCH_FILES))
